"""Unattended upgrades configuration (/etc/apt/apt.conf.d/*)."""

from __future__ import annotations

import re
import shutil
from typing import Dict, List, Optional

from ..paths import AUTO_UPGRADES_FILE, UNATTENDED_FILE, UNATTENDED_LOG
from ..util import read_text, write_text

SETTING_RE = re.compile(
    r'^\s*(?P<key>[A-Za-z0-9:_-]+)\s+(?P<value>"[^"]*"|[^;]+)\s*;',
    re.M,
)
ORIGINS_KEY = "Unattended-Upgrade::Allowed-Origins"


def parse_settings(text: str) -> Dict[str, str]:
    """Parse simple `Key "value";` apt.conf settings (last one wins)."""
    values: Dict[str, str] = {}
    for match in SETTING_RE.finditer(text):
        value = match.group("value").strip()
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        values[match.group("key")] = value
    return values


def upsert_setting(text: str, key: str, value: str) -> str:
    """Replace or append a `Key "value";` line, preserving comments."""
    new_line = f'{key} "{value}";'
    lines = text.splitlines()
    pattern = re.compile(rf'^\s*{re.escape(key)}\s+')
    for index, line in enumerate(lines):
        if pattern.match(line):
            lines[index] = new_line
            return "\n".join(lines) + ("\n" if text.endswith("\n") or lines else "")
    if lines and lines[-1] != "":
        lines.append("")
    lines.append(new_line)
    return "\n".join(lines) + "\n"


def parse_allowed_origins(text: str) -> List[str]:
    """Collect the quoted entries of the Allowed-Origins block.

    Quote-aware on purpose: origin strings contain braces ("${distro_id}"),
    so a naive brace match truncates the block.
    """
    origins: List[str] = []
    in_block = False
    for line in text.splitlines():
        if not in_block:
            marker = line.find(ORIGINS_KEY)
            if marker == -1:
                continue
            in_block = True
            line = line[marker + len(ORIGINS_KEY) :]
        current: List[str] = []
        in_quote = False
        closed = False
        for char in line:
            if char == '"':
                if in_quote:
                    origins.append("".join(current))
                    current = []
                    in_quote = False
                else:
                    in_quote = True
                continue
            if in_quote:
                current.append(char)
            elif char == "}":
                closed = True
                break
        if closed:
            break
    return origins


def log_tail(limit: int = 200) -> List[str]:
    try:
        lines = UNATTENDED_LOG.read_text(encoding="utf-8", errors="replace").splitlines()
    except FileNotFoundError:
        return []
    return lines[-limit:]


def package_installed() -> bool:
    """Is the unattended-upgrades package present? (Default on Ubuntu, optional on Debian.)"""
    return shutil.which("unattended-upgrade") is not None or UNATTENDED_FILE.exists()


def status() -> Dict[str, object]:
    auto = parse_settings(read_text(AUTO_UPGRADES_FILE))
    conf = parse_settings(read_text(UNATTENDED_FILE))
    return {
        "package_installed": package_installed(),
        "enabled": auto.get("APT::Periodic::Unattended-Upgrade", "0") == "1",
        "update_lists": auto.get("APT::Periodic::Update-Package-Lists", "0") == "1",
        "update_frequency_days": auto.get("APT::Periodic::Update-Package-Lists", "1"),
        "auto_reboot": conf.get("Unattended-Upgrade::Automatic-Reboot", "false") == "true",
        "auto_reboot_time": conf.get("Unattended-Upgrade::Automatic-Reboot-Time", ""),
        "remove_unused": conf.get("Unattended-Upgrade::Remove-Unused-Kernel-Packages", "true") == "true",
        "remove_unused_dependencies": conf.get("Unattended-Upgrade::Remove-Unused-Dependencies", "false") == "true",
        "allowed_origins": parse_allowed_origins(read_text(UNATTENDED_FILE)),
        "log": log_tail(),
        "files": {
            "auto_upgrades": str(AUTO_UPGRADES_FILE),
            "unattended": str(UNATTENDED_FILE),
        },
    }


def apply_settings(
    *,
    enabled: bool,
    update_frequency_days: Optional[str] = None,
    auto_reboot: Optional[bool] = None,
    auto_reboot_time: Optional[str] = None,
    remove_unused: Optional[bool] = None,
    remove_unused_dependencies: Optional[bool] = None,
) -> Dict[str, object]:
    """Write the unattended-upgrades configuration."""
    frequency = update_frequency_days or parse_settings(read_text(AUTO_UPGRADES_FILE)).get(
        "APT::Periodic::Update-Package-Lists", "1"
    )
    auto_text = read_text(AUTO_UPGRADES_FILE) or (
        "// Generated by LinuStart\n// Periodic upgrade settings\n"
    )
    auto_text = upsert_setting(auto_text, "APT::Periodic::Unattended-Upgrade", "1" if enabled else "0")
    auto_text = upsert_setting(auto_text, "APT::Periodic::Update-Package-Lists", str(frequency))
    write_text(AUTO_UPGRADES_FILE, auto_text)

    conf_text = read_text(UNATTENDED_FILE)
    if conf_text:
        if auto_reboot is not None:
            conf_text = upsert_setting(
                conf_text,
                "Unattended-Upgrade::Automatic-Reboot",
                "true" if auto_reboot else "false",
            )
        if auto_reboot_time is not None:
            conf_text = upsert_setting(
                conf_text, "Unattended-Upgrade::Automatic-Reboot-Time", auto_reboot_time
            )
        if remove_unused is not None:
            conf_text = upsert_setting(
                conf_text,
                "Unattended-Upgrade::Remove-Unused-Kernel-Packages",
                "true" if remove_unused else "false",
            )
        if remove_unused_dependencies is not None:
            conf_text = upsert_setting(
                conf_text,
                "Unattended-Upgrade::Remove-Unused-Dependencies",
                "true" if remove_unused_dependencies else "false",
            )
        write_text(UNATTENDED_FILE, conf_text)
    return status()
