"""Tests for resolver status: resolv.conf parsing, manager detection, warnings."""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from linustart.modules.network import (  # noqa: E402
    dns_setting_applies,
    parse_resolv_conf,
    resolver_manager,
    resolver_summary,
)

# The file that started this feature: dhcpcd regenerated it and wrote no
# nameservers at all, so the machine resolves nothing.
DHCPCD_EMPTY = """# Generated by dhcpcd
# /etc/resolv.conf.head can replace this line
# /etc/resolv.conf.tail can replace this line
"""

RESOLVCONF_SAMPLE = """# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
search lan
nameserver 192.168.10.1
nameserver 1.1.1.1
"""

RESOLVED_SAMPLE = """# This is /run/systemd/resolve/stub-resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
nameserver 127.0.0.53
options edns0 trust-ad
search home
"""

NM_SAMPLE = """# Generated by NetworkManager
; semicolon comments are valid resolv.conf syntax too
domain office.example
nameserver 10.0.0.53
"""


def test_parse_resolv_conf_dhcpcd_with_no_nameservers():
    parsed = parse_resolv_conf(DHCPCD_EMPTY)
    assert parsed["nameservers"] == []
    assert parsed["search"] == []
    assert parsed["generated_by"] == "dhcpcd"


def test_parse_resolv_conf_resolvconf_sample():
    parsed = parse_resolv_conf(RESOLVCONF_SAMPLE)
    assert parsed["nameservers"] == ["192.168.10.1", "1.1.1.1"]
    assert parsed["search"] == ["lan"]
    assert parsed["generated_by"] == "resolvconf"


def test_parse_resolv_conf_resolved_stub():
    parsed = parse_resolv_conf(RESOLVED_SAMPLE)
    assert parsed["nameservers"] == ["127.0.0.53"]
    assert parsed["search"] == ["home"]
    assert parsed["generated_by"] == "systemd-resolved"


def test_parse_resolv_conf_networkmanager_and_domain_fallback():
    parsed = parse_resolv_conf(NM_SAMPLE)
    assert parsed["nameservers"] == ["10.0.0.53"]
    assert parsed["search"] == ["office.example"]  # from `domain`, comments skipped
    assert parsed["generated_by"] == "NetworkManager"


def test_parse_resolv_conf_handles_missing_and_garbage():
    assert parse_resolv_conf("") == {"nameservers": [], "search": [], "generated_by": ""}
    parsed = parse_resolv_conf("nameserver\nsearch\ndomain\nhello world\n")
    assert parsed == {"nameservers": [], "search": [], "generated_by": ""}
    # entries are kept verbatim even when they are not addresses
    assert parse_resolv_conf("nameserver 1.1.1.1.1")["nameservers"] == ["1.1.1.1.1"]


def test_resolver_manager_priority():
    # The generator comment wins even when other resolvers are installed.
    assert (
        resolver_manager("dhcpcd", False, True, True, True) == "dhcpcd"
    )
    # Ubuntu default: stub address in the file plus a running resolved.
    assert resolver_manager("", True, True, True, True) == "systemd-resolved"
    # Without a comment, an installed resolvconf is the most likely owner.
    assert resolver_manager("", False, False, True, True) == "resolvconf"
    # resolved running but no stub address and no resolvconf
    assert resolver_manager("", False, True, False, False) == "systemd-resolved"
    # dhcpcd installed but nothing else known
    assert resolver_manager("", False, None, False, True) == "dhcpcd"
    # nobody claims the file: a plain static one
    assert resolver_manager("", False, False, False, False) == "static"


def test_dns_setting_applies_matrix():
    # NetworkManager and netplan always have a hook to carry the servers.
    for manager in ["static", "dhcpcd", "systemd-resolved", "resolvconf"]:
        assert dns_setting_applies("NetworkManager", manager, False) is True
        assert dns_setting_applies("netplan", manager, False) is True
    # ifupdown needs resolvconf or an equivalent shim...
    assert dns_setting_applies("ifupdown", "resolvconf", True) is True
    assert dns_setting_applies("ifupdown", "static", True) is True
    assert dns_setting_applies("ifupdown", "static", False) is False
    # ...and systemd-resolved does not read dns-nameservers either.
    assert dns_setting_applies("ifupdown", "systemd-resolved", False) is False
    # dhcpcd owns the file and ignores dns-nameservers even when a
    # resolvconf binary happens to be installed.
    assert dns_setting_applies("ifupdown", "dhcpcd", True) is False


def test_summary_reports_the_dhcpcd_trap():
    summary = resolver_summary(
        "ifupdown", parse_resolv_conf(DHCPCD_EMPTY),
        resolved_active=False, has_resolvconf=False, has_dhcpcd=True,
    )
    assert summary["manager"] == "dhcpcd"
    assert summary["dns_setting_applies"] is False
    text = " ".join(summary["warnings"])
    assert "no nameserver" in text
    assert "dhcpcd" in text and "domain_name_servers" in text


def test_summary_is_quiet_when_everything_is_fine():
    summary = resolver_summary(
        "ifupdown", parse_resolv_conf(RESOLVCONF_SAMPLE),
        resolved_active=False, has_resolvconf=True, has_dhcpcd=False,
    )
    assert summary["dns_setting_applies"] is True
    assert summary["warnings"] == []


def test_summary_flags_invalid_nameserver_entries():
    parsed = parse_resolv_conf("nameserver 1.1.1.1.1\nnameserver 8.8.8.8\n")
    summary = resolver_summary(
        "netplan", parsed,
        resolved_active=True, has_resolvconf=False, has_dhcpcd=False,
    )
    assert summary["dns_setting_applies"] is True
    assert any("1.1.1.1.1" in warning for warning in summary["warnings"])


def test_summary_flags_empty_resolv_conf_on_every_backend():
    for backend in ["ifupdown", "netplan", "NetworkManager"]:
        summary = resolver_summary(
            backend, parse_resolv_conf(""),
            resolved_active=False, has_resolvconf=False, has_dhcpcd=False,
        )
        assert any("no nameserver" in warning for warning in summary["warnings"])


if __name__ == "__main__":
    for name, func in sorted(list(globals().items())):
        if name.startswith("test_") and callable(func):
            func()
            print(f"ok: {name}")
    print("all resolver tests passed")
