"""Tests for the resolvconf setup job: what it registers and when it backs out."""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from linustart.modules import resolvconf  # noqa: E402

DHCPCD_LEFTOVER = """# Generated by dhcpcd from ens18.dhcp
# /etc/resolv.conf.head can replace this line
nameserver 1.1.1.1
nameserver 8.8.8.8
"""


def test_setup_is_offered_only_where_the_panel_dns_does_not_apply():
    assert resolvconf.setup_offered("ifupdown", {"dns_setting_applies": False, "has_resolvconf": False})
    assert not resolvconf.setup_offered("ifupdown", {"dns_setting_applies": True, "has_resolvconf": False})
    assert not resolvconf.setup_offered("ifupdown", {"dns_setting_applies": False, "has_resolvconf": True})
    assert not resolvconf.setup_offered("netplan", {"dns_setting_applies": False, "has_resolvconf": False})


def test_records_follow_ifupdowns_naming_and_drop_junk():
    interfaces = [
        {"name": "ens18", "method": "static", "dns": ["192.168.20.5", "192.168.20.5", "bogus"]},
        {"name": "ens19", "method": "dhcp", "dns": []},
        {"name": "-evil", "dns": ["1.1.1.1"]},
    ]
    assert resolvconf.records_for(interfaces, ["1.1.1.1"]) == [("ens18.inet", ["192.168.20.5"])]


def test_the_servers_in_use_carry_over_when_no_interface_names_any():
    interfaces = [{"name": "ens18", "method": "dhcp", "dns": []}]
    assert resolvconf.records_for(interfaces, ["1.1.1.1", "nonsense"]) == [
        (resolvconf.FALLBACK_RECORD, ["1.1.1.1"])
    ]
    assert resolvconf.records_for(interfaces, []) == []


def test_record_text():
    assert resolvconf.record_text(["192.168.20.5", "1.1.1.1"]) == "nameserver 192.168.20.5\nnameserver 1.1.1.1\n"


def _fake_machine(monkeypatch, tmp_path, *, result_text):
    resolv = tmp_path / "resolv.conf"
    resolv.write_text(DHCPCD_LEFTOVER, encoding="utf-8")
    monkeypatch.setattr(resolvconf, "RESOLV_CONF_FILE", resolv)

    async def detect():
        return "ifupdown"

    async def config(_backend=None):
        return {"interfaces": [{"name": "ens18", "method": "static", "dns": ["192.168.20.5"]}]}

    monkeypatch.setattr(resolvconf.network, "detect_backend", detect)
    monkeypatch.setattr(resolvconf.network, "get_config", config)
    calls = []

    def run(argv, stdin_text=None):
        calls.append((list(argv), stdin_text))
        if argv[:2] == ["resolvconf", "-u"]:
            # what installing resolvconf does: the file becomes generated
            resolv.unlink()
            resolv.write_text(result_text, encoding="utf-8")
        return 0

    monkeypatch.setattr(resolvconf, "_run", run)
    return resolv, calls


def test_setup_installs_and_registers_the_configured_servers(monkeypatch, tmp_path):
    resolv, calls = _fake_machine(
        monkeypatch, tmp_path, result_text="# generated by resolvconf(8)\nnameserver 192.168.20.5\n"
    )
    assert resolvconf.cmd_setup() == 0
    assert calls[0][0][:2] == ["apt-get", "-y"] and calls[0][0][-1] == "resolvconf"
    assert (["resolvconf", "-a", "ens18.inet"], "nameserver 192.168.20.5\n") in calls
    assert "192.168.20.5" in resolv.read_text(encoding="utf-8")


def test_setup_puts_the_old_file_back_rather_than_leave_no_nameserver(monkeypatch, tmp_path):
    resolv, _ = _fake_machine(monkeypatch, tmp_path, result_text="# generated by resolvconf(8)\n")
    assert resolvconf.cmd_setup() == 1
    assert resolv.read_text(encoding="utf-8") == DHCPCD_LEFTOVER
    assert not resolv.is_symlink()


def test_setup_refuses_other_backends(monkeypatch):
    async def detect():
        return "netplan"

    monkeypatch.setattr(resolvconf.network, "detect_backend", detect)
    monkeypatch.setattr(resolvconf, "_run", lambda *a, **k: (_ for _ in ()).throw(AssertionError("ran")))
    assert resolvconf.cmd_setup() == 1


def test_the_job_runs_this_module():
    argv = resolvconf.command()
    assert argv[1:] == ["-m", "linustart.modules.resolvconf", "setup"]
