"""Tests for the resolvconf setup job: what it registers and when it backs out."""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from linustart.modules import resolvconf  # noqa: E402

DHCPCD_LEFTOVER = """# Generated by dhcpcd from ens18.dhcp
# /etc/resolv.conf.head can replace this line
search lan example.com
nameserver 1.1.1.1
nameserver 8.8.8.8
options edns0 rotate
"""

OFFERED = {"dns_setting_applies": False, "has_resolvconf": False, "manager": "dhcpcd"}


def test_setup_is_offered_only_where_the_panel_dns_does_not_apply():
    assert resolvconf.setup_offered("ifupdown", OFFERED)
    assert resolvconf.setup_offered("ifupdown", {**OFFERED, "manager": "static"})
    assert not resolvconf.setup_offered("ifupdown", {**OFFERED, "dns_setting_applies": True})
    assert not resolvconf.setup_offered("ifupdown", {**OFFERED, "has_resolvconf": True})
    assert not resolvconf.setup_offered("netplan", OFFERED)
    # never beside a resolver that already owns the file
    assert not resolvconf.setup_offered("ifupdown", {**OFFERED, "resolved_active": True})
    for manager in ("systemd-resolved", "NetworkManager", "resolvconf"):
        assert not resolvconf.setup_offered("ifupdown", {**OFFERED, "manager": manager})


def test_install_never_removes_a_conflicting_package():
    argv = resolvconf.install_command()
    assert argv[:3] == ["apt-get", "-y", "--no-remove"]
    assert argv[-2:] == ["install", "resolvconf"]


def test_search_domains_and_options_carry_over():
    assert resolvconf.carried_search(DHCPCD_LEFTOVER) == ["lan", "example.com"]
    assert resolvconf.carried_search("search ok bad;rm\n") == ["ok"]
    assert resolvconf.carried_options(DHCPCD_LEFTOVER) == ["options edns0 rotate"]
    assert resolvconf.carried_options("options\nsortlist 10.0.0.0/8\n") == ["sortlist 10.0.0.0/8"]


def test_records_follow_ifupdowns_naming_and_drop_junk():
    interfaces = [
        {"name": "ens18", "method": "static", "dns": ["192.168.20.5", "192.168.20.5", "bogus"]},
        {"name": "ens19", "method": "dhcp", "dns": []},
        {"name": "-evil", "dns": ["1.1.1.1"]},
    ]
    assert resolvconf.records_for(interfaces, ["1.1.1.1"]) == [("ens18.inet", ["192.168.20.5"])]


def test_the_servers_in_use_carry_over_when_no_interface_names_any():
    interfaces = [{"name": "ens18", "method": "dhcp", "dns": []}]
    assert resolvconf.records_for(interfaces, ["1.1.1.1", "nonsense"]) == [
        (resolvconf.FALLBACK_RECORD, ["1.1.1.1"])
    ]
    assert resolvconf.records_for(interfaces, []) == []


def test_record_text():
    assert resolvconf.record_text(["192.168.20.5", "1.1.1.1"]) == "nameserver 192.168.20.5\nnameserver 1.1.1.1\n"
    assert resolvconf.record_text(["192.168.20.5"], ["lan"]) == "nameserver 192.168.20.5\nsearch lan\n"


def _fake_machine(monkeypatch, tmp_path, *, result_text, active=(), immutable=False, apt_rc=0):
    resolv = tmp_path / "resolv.conf"
    resolv.write_text(DHCPCD_LEFTOVER, encoding="utf-8")
    monkeypatch.setattr(resolvconf, "RESOLV_CONF_FILE", resolv)
    monkeypatch.setattr(resolvconf, "BASE_FILE", tmp_path / "resolvconf" / "base")
    monkeypatch.setattr(resolvconf, "is_immutable", lambda path: immutable)
    backups = []
    monkeypatch.setattr(resolvconf, "backup", lambda path: backups.append(path.read_text(encoding="utf-8")))

    async def detect():
        return "ifupdown"

    async def config(_backend=None):
        return {"interfaces": [{"name": "ens18", "method": "static", "dns": ["192.168.20.5"]}]}

    monkeypatch.setattr(resolvconf.network, "detect_backend", detect)
    monkeypatch.setattr(resolvconf.network, "get_config", config)
    calls = []

    def run(argv, stdin_text=None):
        calls.append((list(argv), stdin_text))
        if argv[0] == "systemctl":
            return 0 if argv[-1] in active else 3
        if argv[0] == "apt-get":
            if apt_rc == 0:
                return 0
            resolv.unlink()  # a half-done install that already swapped the file
            resolv.write_text("# generated by resolvconf(8)\n", encoding="utf-8")
            return apt_rc
        if argv[:2] == ["resolvconf", "-u"]:
            # what installing resolvconf does: the file becomes generated
            resolv.unlink()
            resolv.write_text(result_text, encoding="utf-8")
        return 0

    monkeypatch.setattr(resolvconf, "_run", run)
    return resolv, calls, backups


def test_setup_installs_and_registers_the_configured_servers(monkeypatch, tmp_path):
    resolv, calls, backups = _fake_machine(
        monkeypatch, tmp_path, result_text="# generated by resolvconf(8)\nnameserver 192.168.20.5\n"
    )
    assert resolvconf.cmd_setup() == 0
    assert backups == [DHCPCD_LEFTOVER]
    apt = [argv for argv, _ in calls if argv[0] == "apt-get"]
    assert apt and "--no-remove" in apt[0] and apt[0][-1] == "resolvconf"
    assert (["resolvconf", "-a", "ens18.inet"], "nameserver 192.168.20.5\nsearch lan example.com\n") in calls
    assert resolvconf.BASE_FILE.read_text(encoding="utf-8") == "options edns0 rotate\n"
    assert "192.168.20.5" in resolv.read_text(encoding="utf-8")


def test_setup_leaves_an_existing_base_file_alone(monkeypatch, tmp_path):
    _fake_machine(monkeypatch, tmp_path, result_text="nameserver 192.168.20.5\n")
    resolvconf.BASE_FILE.parent.mkdir(parents=True)
    resolvconf.BASE_FILE.write_text("options ndots:2\n", encoding="utf-8")
    assert resolvconf.cmd_setup() == 0
    assert resolvconf.BASE_FILE.read_text(encoding="utf-8") == "options ndots:2\n"


def test_setup_refuses_beside_another_resolver_or_an_immutable_file(monkeypatch, tmp_path):
    for kwargs in ({"active": ("systemd-resolved",)}, {"active": ("NetworkManager",)}, {"immutable": True}):
        resolv, calls, backups = _fake_machine(monkeypatch, tmp_path, result_text="", **kwargs)
        assert resolvconf.cmd_setup() == 1, kwargs
        assert not [argv for argv, _ in calls if argv[0] in ("apt-get", "resolvconf")]
        assert backups == []
        assert resolv.read_text(encoding="utf-8") == DHCPCD_LEFTOVER


def test_a_failed_install_puts_a_swapped_file_back(monkeypatch, tmp_path):
    resolv, _, _ = _fake_machine(monkeypatch, tmp_path, result_text="", apt_rc=100)
    assert resolvconf.cmd_setup() == 1
    assert resolv.read_text(encoding="utf-8") == DHCPCD_LEFTOVER


def test_setup_puts_the_old_file_back_rather_than_leave_no_nameserver(monkeypatch, tmp_path):
    resolv, _, _ = _fake_machine(monkeypatch, tmp_path, result_text="# generated by resolvconf(8)\n")
    assert resolvconf.cmd_setup() == 1
    assert resolv.read_text(encoding="utf-8") == DHCPCD_LEFTOVER
    assert not resolv.is_symlink()


def test_setup_refuses_other_backends(monkeypatch):
    async def detect():
        return "netplan"

    monkeypatch.setattr(resolvconf.network, "detect_backend", detect)
    monkeypatch.setattr(resolvconf, "_run", lambda *a, **k: (_ for _ in ()).throw(AssertionError("ran")))
    assert resolvconf.cmd_setup() == 1


def test_the_job_runs_this_module():
    argv = resolvconf.command()
    assert argv[1:] == ["-m", "linustart.modules.resolvconf", "setup"]
